// Language copy lives here so the static HTML stays simple to edit.
const translations = {
  en: {
    "meta.title": "Film details",
    "meta.filmType": "Film type",
    "meta.duration": "Duration",
    "meta.genre": "Genre",
    "meta.subGenre": "Sub-Genre",
    "meta.year": "Year",
    "unfurnished.meta.type": "Narrative",
    "unfurnished.meta.duration": "1m 30s",
    "unfurnished.meta.genre": "Drama",
    "unfurnished.meta.year": "2026",
    "strange.meta.type": "Narrative",
    "strange.meta.duration": "1m 30s",
    "strange.meta.genre": "Thriller",
    "strange.meta.subGenre": "Suspense",
    "strange.meta.year": "2026",
    "reviver.meta.type": "Narrative",
    "reviver.meta.duration": "1m",
    "reviver.meta.genre": "Drama",
    "reviver.meta.subGenre": "Existential Drama",
    "reviver.meta.year": "2026",
    "elevator.meta.type": "Narrative",
    "elevator.meta.duration": "4m",
    "elevator.meta.genre": "Horror",
    "elevator.meta.subGenre": "Psychological Horror",
    "elevator.meta.year": "2026",
    "project.meta.type": "Narrative",
    "project.meta.duration": "2m",
    "project.meta.genre": "Drama",
    "project.meta.subGenre": "Social Impact",
    "project.meta.year": "2026",
    "lesOmbres.meta.type": "Book trailer",
    "lesOmbres.meta.duration": "1m",
    "lesOmbres.meta.genre": "Crime",
    "lesOmbres.meta.subGenre": "Noir Thriller",
    "lesOmbres.meta.year": "2026",
    "ultimoAliento.meta.type": "Documentary",
    "ultimoAliento.meta.duration": "1m 30s",
    "ultimoAliento.meta.genre": "Trailer",
    "ultimoAliento.meta.subGenre": "Educational",
    "ultimoAliento.meta.year": "2025",
    "legadoIa.meta.type": "Concept Trailer",
    "legadoIa.meta.duration": "1m 36s",
    "legadoIa.meta.genre": "Trailer",
    "legadoIa.meta.subGenre": "Educational",
    "legadoIa.meta.year": "2024",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.jury": "Jury Member",
    "nav.works": "Works",
    "nav.partnerships": "Creative Partnerships",
    "nav.platform": "Platform",
    "nav.contact": "Contact",
    "hero.eyebrow": "Raül Torres",
    "hero.title": "Creative Portfolio",
    "hero.subtitle": "Filmmaker IA | AI Educator | AI Film Festival Jury Member | Dreamina Creative Partner Program | Founding Creator Shoowai | Shaike Certified Creator",
    "hero.cta": "View my work",
    "about.eyebrow": "About",
    "about.title": "A camera, a story, a new language",
    "about.p1": "I am an audiovisual creator working at the intersection of storytelling and artificial intelligence.",
    "about.p2": "I began my journey in cinema in 2002, creating guerrilla-style short films with minimal resources, but with a deep attention to narrative and visual expression. After a period away from the medium, I returned with a renewed perspective, incorporating artificial intelligence as a creative tool capable of expanding the possibilities of audiovisual language without replacing the human vision behind each story.",
    "about.p3": "My work explores how technology can serve emotion, meaning and cinematic language. I am especially interested in creating pieces that connect with audiences on a human level, using innovative techniques to strengthen storytelling rather than distract the viewer from it.",
    "about.p4": "Projects like POWER OFF reflect this philosophy: combining visual experimentation, technological exploration and a clear narrative intention with a strong emotional core.",
    "about.p5": "This portfolio brings together my recent work in AI-driven filmmaking, where each project represents a new step in the search for contemporary forms of audiovisual expression, always with narrative and emotion as the central axis.",
    "about.quote": "\"GenAI tools expire quickly, but storytelling lasts forever\"",
    "about.noteLabel": "Creative focus",
    "about.note": "Cinema, emotional realism and AI-assisted audiovisual exploration.",
    "project.title": "POWER OFF",
    "project.description1": "On one side, a mother and daughter survive war. On the other, they live in peace, unaware. Same moments. Two realities in sync… until everything breaks.",
    "project.watch": "WATCH VIDEO",
    "project.awardsTitle": "Awards",
    "project.award1Link": "Best Concept Award",
    "project.award1Rest": ": LAAIMPA WINNERS APRIL 2026 - Los Ángeles",
    "project.award2": "Best AI Film: Zeal International Film Festival 2026 - Paris",
    "project.awardInterview": "Watch POWER interview",
    "project.finalistTitle": "Finalist",
    "project.finalist1": "Finalist AI Movie Awards - Mallorca",
    "project.finalist2": "Quarter-Finalist AI Film Awards INDIA",
    "project.finalist3": "Finalist AI London Film Festival 2026",
    "project.selectionTitle": "Official Selection",
    "project.selection1": "BAIFF - Burano Artificial Intelligence Film Festival",
    "project.selection2": "AI Film Awards in Cannes 2026",
    "project.selection3": "TODO ES PROMPT - Chile",
    "project.selection4": "IA en CORTO - Chile",
    "project.selection5": "ICJ International Film Award - Ukraine",
    "project.selection6": "SEOUL INTERNATIONAL AI Film Festival",
    "project.platformsTitle": "Platforms where POWER OFF is featured",
    "project.platform1Name": "JAMESDRAKE TV",
    "project.platform1Description": "James Drake TV (JDTV) is a creative platform and YouTube channel focused on the dissemination of art, history, and science through the use of artificial intelligence to create cinematic narratives.",
    "project.platform2Name": "Cinferno",
    "project.platform2Description": "Selected to be part of the showcase of the year's top 100 AI films.",
    "project.techTitle": "Technologies used",
    "project.tech1": "Character and Environment Consistency by Nano Banana Pro",
    "project.tech2": "AI Video Generation Model by Kling 3.0",
    "project.tech3": "Sound by Eleven Labs",
    "project.tech4": "Music by Suno AI",
    "project.tech5": "Editing by Filmora 14",
    "unfurnished.title": "UNFURNISHED",
    "unfurnished.description1": "A couple buys an unfurnished apartment to begin a new chapter of their lives together. As the empty space gradually fills with furniture, memories, and everyday objects, the home evolves alongside the life they build within its walls.",
    "unfurnished.watch": "WATCH VIDEO",
    "unfurnished.techTitle": "Technologies used",
    "unfurnished.tech1": "Assisted by ChatGPT 5.5",
    "unfurnished.tech2": "Character & Environment Consistency by GPT Image 2.0",
    "unfurnished.tech3": "AI Video Generation by Model Seedance 2.0 (Dreamina AI)",
    "unfurnished.tech4": "Editing by DaVinci Resolve",
    "strange.title": "STRANGE",
    "strange.description1": "In an abandoned factory, an unknown presence flees relentlessly to avoid capture. A relentless pursuit where fear and uncertainty shadow every step.",
    "strange.watch": "WATCH VIDEO",
    "strange.techTitle": "Technologies used",
    "strange.tech1": "Assisted by ChatGPT 5.5",
    "strange.tech2": "Character & Environment Design by Midjourney 8.1",
    "strange.tech3": "Character & Environment Consistency by GPT Image 2.0",
    "strange.tech4": "AI Video Generation by Model Seedance 2.0",
    "strange.tech5": "Editing by DaVinci Resolve",
    "reviver.title": "REVIVER",
    "reviver.description1": "REVIVEЯ is a reflection on the fragility of human decisions, the weight of fate, and the profound impact of those fleeting moments that can change a life forever.",
    "reviver.description2": "An intimate story about hope, second chances, and the thin line between an ordinary moment and an irreversible turning point.",
    "reviver.watch": "WATCH VIDEO",
    "reviver.techTitle": "Technologies used",
    "reviver.tech1": "Assisted by ChatGPT 5.5",
    "reviver.tech2": "Character & Environment Design by Midjourney 8.1",
    "reviver.tech3": "Character & Environment Consistency by GPT Image 2.0",
    "reviver.tech4": "AI Video Generation Model by Seedance 2.0",
    "reviver.tech5": "Editing by Filmora 14",
    "elevator.title": "ELEVATOR",
    "elevator.description1": "A man enters an old elevator on a rainy night.",
    "elevator.description2": "As it descends, an unsettling sense of strangeness begins to take hold of him.",
    "elevator.description3": "Through silence, lingering glances, and an increasingly oppressive atmosphere, the journey leads him toward a place where nothing is quite as familiar as it seems.",
    "elevator.watch": "WATCH VIDEO",
    "elevator.finalistTitle": "Finalist",
    "elevator.finalist1": "SEOUL INTERNATIONAL AI Film Festival 2026",
    "elevator.finalist2": "Finalist AI London Film Festival 2026",
    "elevator.finalist3": "Zeal International Film Festival 2026",
    "elevator.nomineeTitle": "Nominee",
    "elevator.nominee1Link": "Best Horror",
    "elevator.nominee1Rest": ": LAAIMPA JUNE 2026 - Los Ángeles",
    "elevator.techTitle": "Technologies used",
    "elevator.tech1": "Assisted by ChatGPT 5.5",
    "elevator.tech2": "Character and Environment Design by Midjourney 8.1",
    "elevator.tech3": "Character and Environment Consistency by GPT Image 2.0",
    "elevator.tech4": "AI Video Generation Model by Seedance 2.0",
    "elevator.tech5": "Editing by Filmora 14",
    "lesOmbres.title": "Les ombres que ens acompanyen",
    "lesOmbres.description1": "Book trailer created for writer Cesc Cornet for his novel \"Les ombres que ens acompanyen\".",
    "lesOmbres.description2": "Three stories. Two cities. No apparent connection... and a breathtaking finale.",
    "lesOmbres.description3": "A multi-threaded thriller that will keep you on edge.",
    "lesOmbres.description4": "A thriller set between Barcelona and Vizcaya, where three seemingly unrelated cases gradually intertwine until they converge in a heart-stopping ending. Pure adrenaline.",
    "lesOmbres.watch": "WATCH VIDEO",
    "lesOmbres.techTitle": "Technologies used",
    "lesOmbres.tech1": "Character and Environment Consistency by Nano Banana Pro",
    "lesOmbres.tech2": "AI Video Generation Model Seedance by Veo 3.1",
    "lesOmbres.tech3": "Music by Suno",
    "lesOmbres.tech4": "Editing by Filmora 14",
    "ultimoAliento.title": "El último aliento",
    "ultimoAliento.description1": "A powerful micro-documentary exploring the devastating effects of plastic waste on our oceans and the urgent need to protect marine life.",
    "ultimoAliento.watch": "WATCH VIDEO",
    "ultimoAliento.techTitle": "Technologies used",
    "ultimoAliento.tech1": "AI Video Generation Model Seedance by Veo 2",
    "ultimoAliento.tech2": "Sound by created with MMAudio (local)",
    "ultimoAliento.tech3": "Voice by Eleven Labs",
    "ultimoAliento.tech4": "Music by Suno",
    "ultimoAliento.tech5": "Editing by Filmora 14",
    "legadoIa.title": "Trailer: El legado de la IA",
    "legadoIa.description1": "A Cinematic Concept Trailer Created Entirely with Artificial Intelligence.",
    "legadoIa.watch": "WATCH VIDEO",
    "legadoIa.techTitle": "Technologies used",
    "legadoIa.tech1": "Assisted by ChatGPT 4",
    "legadoIa.tech2": "AI Video Generation Model Seedance by Runway",
    "legadoIa.tech3": "Character and Environment Consistency by Flux.1 (Local)",
    "legadoIa.tech4": "Audio by Eleven Labs",
    "legadoIa.tech5": "Music by Suno",
    "legadoIa.tech6": "Editing by Filmora 13",
    "jury.eyebrow": "Jury Member",
    "jury.title": "Jury Member - LAAIMPA Festival 2026",
    "jury.description": "Served as an international jury member for the 2026 edition of the festival, contributing to the evaluation and selection of AI-generated films alongside industry professionals.",
    "jury.certificate": "Official certificate issued by the LAAIMPA Festival Organizing Committee (May 2026).",
    "partnerships.eyebrow": "Creative Partnerships",
    "partnerships.title": "Official member of the Dreamina Creative Partner Program (CPP)",
    "partnerships.p1Start": "Selected as an official",
    "partnerships.linkText": "Dreamina Creative Partner",
    "partnerships.p1Rest": "in recognition of my creative portfolio and work in AI filmmaking. This partnership provides access to advanced tools, early releases and new opportunities for creative collaboration.",
    "partnerships.klingTitle": "Official member of the Kling AI Elite Creators Program",
    "partnerships.klingP1Start": "Selected by",
    "partnerships.klingBrand": "Kling AI",
    "partnerships.klingP1Rest": "in recognition of my creative work in AI filmmaking. As an Elite Creator, I have access to exclusive creator benefits, early access to new features, direct communication with the Kling team, and opportunities to collaborate within a global community of creators.",
    "platform.eyebrow": "Platform",
    "platform.title": "Shoowai Founding Creator",
    "platform.p1": "I have been invited to join Shoowai as a Founding Creator, an international platform dedicated to creators and filmmakers working with artificial intelligence.",
    "platform.p2": "Shoowai is designed as a curated and professional space where creators can showcase their projects, connect with other professionals, offer creative services, and share digital assets within a community focused on quality, innovation, and the new possibilities of AI filmmaking.",
    "platform.cta": "Visit Shoowai",
    "platform.shaikeTitle": "Shaike Certified Creator",
    "platform.shaikeP1Start": "I have been officially recognized as a ",
    "platform.shaikeP1Link": "Shaike Certified Creator",
    "platform.shaikeP1End": ", joining a curated community of AI filmmakers, visual artists, and creative storytellers whose work has been selected for its quality, originality, and innovation in AI-generated content.",
    "platform.shaikeP2": "Shaike is a platform dedicated to showcasing outstanding AI films and visual storytelling projects, connecting creators with a global audience interested in the future of artificial intelligence and creative expression.",
    "platform.shaikeP3": "Through this recognition, I share my work alongside other creators exploring the boundaries of generative filmmaking, AI-assisted storytelling, digital art, and emerging creative technologies.",
    "platform.shaikeCta": "Visit Shaike",
    "contact.eyebrow": "Contact",
    "contact.title": "Follow my work",
    "contact.linkedin": "LinkedIn",
    "contact.instagram": "Instagram",
    "contact.x": "X",
    "contact.tiktok": "TikTok",
    "contact.youtube": "YouTube",
    "footer.copyright": "© 2026 Raül Torres. Creative Portfolio.",
    "footer.tagline": "Cinema with AI, human perspective."
  },
  es: {
    "meta.title": "Datos de la pieza",
    "meta.filmType": "Tipo",
    "meta.duration": "Duración",
    "meta.genre": "Género",
    "meta.subGenre": "Subgénero",
    "meta.year": "Año",
    "unfurnished.meta.type": "Narrativo",
    "unfurnished.meta.duration": "1 min 30 s",
    "unfurnished.meta.genre": "Drama",
    "unfurnished.meta.year": "2026",
    "strange.meta.type": "Narrativo",
    "strange.meta.duration": "1 min 30 s",
    "strange.meta.genre": "Thriller",
    "strange.meta.subGenre": "Suspense",
    "strange.meta.year": "2026",
    "reviver.meta.type": "Narrativo",
    "reviver.meta.duration": "1 min",
    "reviver.meta.genre": "Drama",
    "reviver.meta.subGenre": "Drama existencial",
    "reviver.meta.year": "2026",
    "elevator.meta.type": "Narrativo",
    "elevator.meta.duration": "4 min",
    "elevator.meta.genre": "Terror",
    "elevator.meta.subGenre": "Terror psicológico",
    "elevator.meta.year": "2026",
    "project.meta.type": "Narrativo",
    "project.meta.duration": "2 min",
    "project.meta.genre": "Drama",
    "project.meta.subGenre": "Impacto social",
    "project.meta.year": "2026",
    "lesOmbres.meta.type": "Tráiler literario",
    "lesOmbres.meta.duration": "1 min",
    "lesOmbres.meta.genre": "Crimen",
    "lesOmbres.meta.subGenre": "Thriller noir",
    "lesOmbres.meta.year": "2026",
    "ultimoAliento.meta.type": "Documental",
    "ultimoAliento.meta.duration": "1 min 30 s",
    "ultimoAliento.meta.genre": "Tráiler",
    "ultimoAliento.meta.subGenre": "Educativo",
    "ultimoAliento.meta.year": "2025",
    "legadoIa.meta.type": "Tráiler conceptual",
    "legadoIa.meta.duration": "1 min 36 s",
    "legadoIa.meta.genre": "Tráiler",
    "legadoIa.meta.subGenre": "Educativo",
    "legadoIa.meta.year": "2024",
    "nav.home": "Inicio",
    "nav.about": "Sobre mí",
    "nav.jury": "Jurado",
    "nav.works": "Trabajos",
    "nav.partnerships": "Colaboraciones",
    "nav.platform": "Plataforma",
    "nav.contact": "Contacto",
    "hero.eyebrow": "Raül Torres",
    "hero.title": "Portfolio Creativo",
    "hero.subtitle": "Filmmaker IA | Educador en IA | Jurado de festivales de cine con IA | Programa Dreamina Creative Partner | Creador fundador en Shoowai | Creador certificado en Shaike",
    "hero.cta": "Ver mi trabajo",
    "about.eyebrow": "Sobre mí",
    "about.title": "Una cámara, una historia, un nuevo lenguaje",
    "about.p1": "Soy un creador audiovisual que trabaja en la intersección entre la narración y la inteligencia artificial.",
    "about.p2": "Comencé mi camino en el cine en 2002, creando cortometrajes de guerrilla con recursos mínimos, pero con una profunda atención a la narrativa y a la expresión visual. Tras un periodo alejado del medio, regresé con una mirada renovada, incorporando la inteligencia artificial como una herramienta creativa capaz de ampliar las posibilidades del lenguaje audiovisual sin sustituir la visión humana que existe detrás de cada historia.",
    "about.p3": "Mi trabajo explora cómo la tecnología puede servir a la emoción, al significado y al lenguaje cinematográfico. Me interesa especialmente crear piezas que conecten con el público a nivel humano, utilizando técnicas innovadoras para potenciar la narración en lugar de distraer al espectador de ella.",
    "about.p4": "Proyectos como POWER OFF reflejan esta filosofía: combinar experimentación visual, exploración tecnológica y una intención narrativa clara con un fuerte núcleo emocional.",
    "about.p5": "Este portfolio reúne mi trabajo reciente en cine impulsado por IA, donde cada proyecto representa un nuevo paso en la búsqueda de formas contemporáneas de expresión audiovisual, siempre con la narrativa y la emoción como eje central.",
    "about.quote": "\"Las herramientas de IAG caducan rápido, pero las historias perduran para siempre\"",
    "about.noteLabel": "Enfoque creativo",
    "about.note": "Cine, realismo emocional y exploración audiovisual asistida por IA.",
    "project.title": "POWER OFF",
    "project.description1": "Por un lado, madre e hija sobreviven a la guerra. Por otro, viven en paz, ajenas. Los mismos momentos. Dos realidades sincronizadas… hasta que todo se rompe.",
    "project.watch": "VER VIDEO",
    "project.awardsTitle": "Premios",
    "project.award1Link": "Premio al Mejor Concepto",
    "project.award1Rest": ": LAAIMPA GANADORES ABRIL 2026 - Los Ángeles",
    "project.award2": "Mejor película de IA: Zeal International Film Festival 2026 - Paris",
    "project.awardInterview": "Ver entrevista de POWER",
    "project.finalistTitle": "Finalista",
    "project.finalist1": "Finalista en AI Movie Awards - Mallorca",
    "project.finalist2": "Cuartofinalista en AI Film Awards India",
    "project.finalist3": "Finalista en AI London Film Festival 2026",
    "project.selectionTitle": "Selección oficial",
    "project.selection1": "BAIFF - Burano Artificial Intelligence Film Festival",
    "project.selection2": "AI Film Awards in Cannes 2026",
    "project.selection3": "TODO ES PROMPT - Chile",
    "project.selection4": "IA en CORTO - Chile",
    "project.selection5": "ICJ International Film Award - Ukraine",
    "project.selection6": "SEOUL INTERNATIONAL AI Film Festival",
    "project.platformsTitle": "Plataformas donde aparece POWER OFF",
    "project.platform1Name": "JAMESDRAKE TV",
    "project.platform1Description": "James Drake TV (JDTV) es una plataforma creativa y canal de YouTube centrado en la difusión del arte, la historia y la ciencia mediante el uso de inteligencia artificial para crear narrativas cinematográficas.",
    "project.platform2Name": "Cinferno",
    "project.platform2Description": "Seleccionado para formar parte del escaparate de las 100 mejores películas de IA del año.",
    "project.techTitle": "Tecnologías utilizadas",
    "project.tech1": "Consistencia de personajes y entornos por Nano Banana Pro",
    "project.tech2": "Modelo de generación de video IA por Kling 3.0",
    "project.tech3": "Sonido por Eleven Labs",
    "project.tech4": "Música por Suno AI",
    "project.tech5": "Edición por Filmora 14",
    "unfurnished.title": "UNFURNISHED",
    "unfurnished.description1": "Una pareja compra un apartamento sin amueblar para comenzar una nueva etapa de sus vidas juntos. A medida que el espacio vacío se llena poco a poco de muebles, recuerdos y objetos cotidianos, el hogar evoluciona junto con la vida que construyen entre sus paredes.",
    "unfurnished.watch": "VER VIDEO",
    "unfurnished.techTitle": "Tecnologías utilizadas",
    "unfurnished.tech1": "Asistido por ChatGPT 5.5",
    "unfurnished.tech2": "Consistencia de personajes y entornos por GPT Image 2.0",
    "unfurnished.tech3": "Generación de vídeo IA por Model Seedance 2.0 (Dreamina AI)",
    "unfurnished.tech4": "Edición por DaVinci Resolve",
    "strange.title": "STRANGE",
    "strange.description1": "En una fábrica abandonada, una presencia desconocida huye sin descanso para evitar ser capturada. Una persecución implacable donde el miedo y la incertidumbre acompañan cada paso.",
    "strange.watch": "VER VIDEO",
    "strange.techTitle": "Tecnologías utilizadas",
    "strange.tech1": "Asistido por ChatGPT 5.5",
    "strange.tech2": "Diseño de personajes y entornos por Midjourney 8.1",
    "strange.tech3": "Consistencia de personajes y entornos por GPT Image 2.0",
    "strange.tech4": "Generación de vídeo IA por Model Seedance 2.0",
    "strange.tech5": "Edición por DaVinci Resolve",
    "reviver.title": "REVIVER",
    "reviver.description1": "REVIVEЯ es una reflexión sobre la fragilidad de las decisiones humanas, el peso del destino y el profundo impacto de esos instantes fugaces que pueden cambiar una vida para siempre.",
    "reviver.description2": "Una historia íntima sobre la esperanza, las segundas oportunidades y la fina línea entre un momento ordinario y un punto de inflexión irreversible.",
    "reviver.watch": "VER VIDEO",
    "reviver.techTitle": "Tecnologías utilizadas",
    "reviver.tech1": "Asistido por ChatGPT 5.5",
    "reviver.tech2": "Diseño de personajes y entornos por Midjourney 8.1",
    "reviver.tech3": "Consistencia de personajes y entornos por GPT Image 2.0",
    "reviver.tech4": "Modelo de generación de video IA por Seedance 2.0",
    "reviver.tech5": "Edición por Filmora 14",
    "elevator.title": "ELEVATOR",
    "elevator.description1": "Un hombre entra en un viejo ascensor en una noche lluviosa.",
    "elevator.description2": "Mientras desciende, una inquietante sensación de extrañeza empieza a apoderarse de él.",
    "elevator.description3": "A través del silencio, las miradas sostenidas y una atmósfera cada vez más opresiva, el viaje lo conduce hacia un lugar donde nada resulta tan familiar como parece.",
    "elevator.watch": "VER VIDEO",
    "elevator.finalistTitle": "Finalista",
    "elevator.finalist1": "SEOUL INTERNATIONAL AI Film Festival 2026",
    "elevator.finalist2": "Finalista en AI London Film Festival 2026",
    "elevator.finalist3": "Zeal International Film Festival 2026",
    "elevator.nomineeTitle": "Nominado",
    "elevator.nominee1Link": "Mejor terror",
    "elevator.nominee1Rest": ": LAAIMPA JUNIO 2026 - Los Ángeles",
    "elevator.techTitle": "Tecnologías utilizadas",
    "elevator.tech1": "Asistido por ChatGPT 5.5",
    "elevator.tech2": "Diseño de personajes y entornos por Midjourney 8.1",
    "elevator.tech3": "Consistencia de personajes y entornos por GPT Image 2.0",
    "elevator.tech4": "Modelo de generación de video IA por Seedance 2.0",
    "elevator.tech5": "Edición por Filmora 14",
    "lesOmbres.title": "Les ombres que ens acompanyen",
    "lesOmbres.description1": "Tráiler literario creado para el escritor Cesc Cornet y su novela \"Les ombres que ens acompanyen\".",
    "lesOmbres.description2": "Tres historias. Dos ciudades. Sin conexión aparente... y un desenlace de infarto.",
    "lesOmbres.description3": "Un thriller coral que te mantendrá en tensión.",
    "lesOmbres.description4": "Un thriller ambientado entre Barcelona y Vizcaya, donde tres casos aparentemente inconexos se entrelazan poco a poco hasta converger en un final sobrecogedor. Pura adrenalina.",
    "lesOmbres.watch": "VER VIDEO",
    "lesOmbres.techTitle": "Tecnologías utilizadas",
    "lesOmbres.tech1": "Consistencia de personajes y entornos por Nano Banana Pro",
    "lesOmbres.tech2": "Modelo de generación de video IA Seedance por Veo 3.1",
    "lesOmbres.tech3": "Música por Suno",
    "lesOmbres.tech4": "Edición por Filmora 14",
    "ultimoAliento.title": "El último aliento",
    "ultimoAliento.description1": "Un poderoso microdocumental que explora los efectos devastadores de los residuos plásticos en nuestros océanos y la necesidad urgente de proteger la vida marina.",
    "ultimoAliento.watch": "VER VIDEO",
    "ultimoAliento.techTitle": "Tecnologías utilizadas",
    "ultimoAliento.tech1": "Modelo de generación de video IA Seedance por Veo 2",
    "ultimoAliento.tech2": "Sonido creado con MMAudio (local)",
    "ultimoAliento.tech3": "Voz por Eleven Labs",
    "ultimoAliento.tech4": "Música por Suno",
    "ultimoAliento.tech5": "Edición por Filmora 14",
    "legadoIa.title": "Tráiler: El legado de la IA",
    "legadoIa.description1": "Un tráiler conceptual cinematográfico creado íntegramente con inteligencia artificial.",
    "legadoIa.watch": "VER VIDEO",
    "legadoIa.techTitle": "Tecnologías utilizadas",
    "legadoIa.tech1": "Asistido por ChatGPT 4",
    "legadoIa.tech2": "Modelo de generación de video IA Seedance por Runway",
    "legadoIa.tech3": "Consistencia de personajes y entornos por Flux.1 (Local)",
    "legadoIa.tech4": "Audio por Eleven Labs",
    "legadoIa.tech5": "Música por Suno",
    "legadoIa.tech6": "Edición por Filmora 13",
    "jury.eyebrow": "Miembro del jurado",
    "jury.title": "Miembro del jurado - LAAIMPA Festival 2026",
    "jury.description": "Participé como miembro del jurado internacional en la edición 2026 del festival, contribuyendo a la evaluación y selección de películas generadas con IA junto a profesionales de la industria.",
    "jury.certificate": "Certificado oficial emitido por el Comité Organizador del Festival LAAIMPA (mayo de 2026).",
    "partnerships.eyebrow": "Colaboraciones creativas",
    "partnerships.title": "Miembro oficial del programa Dreamina Creative Partner (CPP)",
    "partnerships.p1Start": "Seleccionado como miembro oficial del programa",
    "partnerships.linkText": "Dreamina Creative Partner",
    "partnerships.p1Rest": "(CPP), en reconocimiento a mi portfolio creativo y mi trabajo en cine con IA. Esta colaboración proporciona acceso a herramientas avanzadas, lanzamientos anticipados y nuevas oportunidades de colaboración creativa.",
    "partnerships.klingTitle": "Miembro oficial del programa Kling AI Elite Creators.",
    "partnerships.klingP1Start": "Seleccionado por",
    "partnerships.klingBrand": "Kling AI",
    "partnerships.klingP1Rest": "en reconocimiento a mi trabajo creativo en cine con IA. Como Elite Creator, tengo acceso a beneficios exclusivos para creadores, acceso anticipado a nuevas funciones, comunicación directa con el equipo de Kling y oportunidades para colaborar dentro de una comunidad global de creadores.",
    "platform.eyebrow": "Plataforma",
    "platform.title": "Creador fundador en Shoowai",
    "platform.p1": "He sido invitado a unirme a Shoowai como Founding Creator, una plataforma internacional dedicada a creadores y cineastas que trabajan con inteligencia artificial.",
    "platform.p2": "Shoowai está concebida como un espacio curado y profesional donde los creadores pueden mostrar sus proyectos, conectar con otros profesionales, ofrecer servicios creativos y compartir recursos digitales dentro de una comunidad centrada en la calidad, la innovación y las nuevas posibilidades del cine con IA.",
    "platform.cta": "Visitar Shoowai",
    "platform.shaikeTitle": "Creador certificado en Shaike",
    "platform.shaikeP1Start": "He sido reconocido oficialmente como ",
    "platform.shaikeP1Link": "Shaike Certified Creator",
    "platform.shaikeP1End": ", uniéndome a una comunidad curada de cineastas de IA, artistas visuales y narradores creativos cuyo trabajo ha sido seleccionado por su calidad, originalidad e innovación en contenido generado con IA.",
    "platform.shaikeP2": "Shaike es una plataforma dedicada a mostrar películas de IA y proyectos de narrativa visual destacados, conectando a creadores con una audiencia global interesada en el futuro de la inteligencia artificial y la expresión creativa.",
    "platform.shaikeP3": "A través de este reconocimiento, comparto mi trabajo junto a otros creadores que exploran los límites del cine generativo, la narrativa asistida por IA, el arte digital y las tecnologías creativas emergentes.",
    "platform.shaikeCta": "Visitar Shaike",
    "contact.eyebrow": "Contacto",
    "contact.title": "Sigue mi trabajo",
    "contact.linkedin": "LinkedIn",
    "contact.instagram": "Instagram",
    "contact.x": "X",
    "contact.tiktok": "TikTok",
    "contact.youtube": "YouTube",
    "footer.copyright": "© 2026 Raül Torres. Portfolio Creativo.",
    "footer.tagline": "Cine con IA, mirada humana."
  }
};

// DOM references
const languageToggle = document.querySelector("#language-toggle");
const languageCodes = document.querySelectorAll("[data-lang-label]");
const menuToggle = document.querySelector(".menu-toggle");
const navigation = document.querySelector("#primary-navigation");
const navigationLinks = navigation.querySelectorAll("a");

let currentLanguage = "en";

// Swap every element marked with data-i18n without reloading the page.
function applyLanguage(language) {
  document.documentElement.lang = language;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    element.textContent = translations[language][key];
  });

  languageCodes.forEach((code) => {
    code.classList.toggle("is-active", code.dataset.langLabel === language);
  });

  const nextLanguage = language === "en" ? "Spanish" : "English";
  languageToggle.setAttribute("aria-label", `Switch language to ${nextLanguage}`);
}

// Mobile navigation closes after selecting an anchor link.
function closeNavigation() {
  document.body.classList.remove("nav-open");
  navigation.classList.remove("is-open");
  menuToggle.classList.remove("is-open");
  menuToggle.setAttribute("aria-expanded", "false");
}

languageToggle.addEventListener("click", () => {
  currentLanguage = currentLanguage === "en" ? "es" : "en";
  applyLanguage(currentLanguage);
});

menuToggle.addEventListener("click", () => {
  const isOpen = navigation.classList.toggle("is-open");
  document.body.classList.toggle("nav-open", isOpen);
  menuToggle.classList.toggle("is-open", isOpen);
  menuToggle.setAttribute("aria-expanded", String(isOpen));
});

navigationLinks.forEach((link) => {
  link.addEventListener("click", closeNavigation);
});

applyLanguage(currentLanguage);
